"""Add comments and activity

Revision ID: ab86ff1bf8b3
Revises: cd31a02683e8
Create Date: 2026-09-22 13:58:20.502797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab86ff1bf8b3'
down_revision: Union[str, Sequence[str], None] = 'cd31a02683e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_activity_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_activity_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_activity_user_id'), ['user_id'], unique=False)

    op.create_table('item_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_comments_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_comments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reminder_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_items_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_foreign_key('fk_items_assignee_id_users', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_assignee_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_items_assignee_id'))
        batch_op.drop_column('assignee_id')
        batch_op.drop_column('reminder_at')
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('item_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_item_comments_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_comments_id'))

    op.drop_table('item_comments')
    with op.batch_alter_table('item_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_activity_user_id'))
        batch_op.drop_index(batch_op.f('ix_item_activity_item_id'))
        batch_op.drop_index(batch_op.f('ix_item_activity_id'))

    op.drop_table('item_activity')
    # ### end Alembic commands ###
