"""Add due_date and tags

Revision ID: ae251c83b9e6
Revises: 903925ac4a5c
Create Date: 2026-09-22 13:30:49.672031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae251c83b9e6'
down_revision: Union[str, Sequence[str], None] = '903925ac4a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_items_due_date'), ['due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_due_date'))
        batch_op.drop_column('tags')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
